test(components): fix types in List.test.tsx
Before this change "yarn typecheck" failed in packages/components with:
```
src/components/list/__tests__/List.test.tsx:107:54 - error TS2322: Ty...
  Type '({ children, className, }: ListItemProps & { children: React....
    Types of parameters '__0' and 'props' are incompatible.
      Type 'ListItemProps' is not assignable to type 'ListItemProps &...
        Property 'children' is missing in type 'ListItemProps' but
        required in type '{ children: ReactNode; }'.

107  const { container } = render(<List items={items} li={CustomLi} />);
                                                         ~~
  src/components/list/__tests__/List.test.tsx:104:26
    104     }: ListItemProps & { children: React.ReactNode }) => (
                                 ~~~~~~~~
    'children' is declared here.
  src/components/list/List.tsx:22:3
    22   li?: React.ComponentType<ListItemProps>;
         ~~
    The expected type comes from property 'li' which is declared here on
    type 'IntrinsicAttributes & Props'
```

refs TH-1409