test(components): fix service.test.ts by fixing listGeneratedPages paths
Before this change running "yarn test" under packages/components on
Windows caused:
```
 FAIL  src/utils/headless-cms/__tests__/service.test.ts >
 headless-cms/service > NextPageRevalidateService > NextPageLister
 functionality > listGeneratedPages should list, deduplicate, and sort
 files recursively
AssertionError: expected [ '/fi\about', '/fi\courses\course1' ] to
strictly equal [ '/fi/about', '/fi/courses/course1' ]

- Expected
+ Received

  [
-   "/fi/about",
-   "/fi/courses/course1",
+   "/fi\\about",
+   "/fi\\courses\\course1",
  ]

 ❯ src/utils/headless-cms/__tests__/service.test.ts:326:23
    324|           path.join(mockProjectRoot, '.next', 'server', 'pag...
    325|         );
    326|         expect(pages).toStrictEqual(
       |                       ^
    327|           ['/fi/about', '/fi/courses/course1'].sort()
    328|         );
```

So the path handling was platform dependent, even though the result was
wanted to be always using forward slashes as path separator. Now
listGeneratedPages converts backslashes to forward slashes, so the
result is the same on Windows too.

refs TH-1409 (path handling was platform dependent, now it's not)