fix(tests): fix events Search "for accessibility violations" test
Also remove 50s timeout from test case as unnecessary.

Previously running events Search.test.tsx tests there was ~output:
```
$ yarn test src/domain/search/eventSearch/advancedSearch/__tests__/
Search.test.tsx --watch

stderr | src/domain/search/eventSearch/advancedSearch/__tests__/
Search.test.tsx > for accessibility violations

Error: Not implemented: HTMLCanvasElement.prototype.getContext (without
installing the canvas npm package)
...

Warning: An update to PlaceSelector inside a test was not wrapped in
act(...).

When testing, code that causes React state updates should be wrapped
into act(...):

act(() => {
  /* fire events that update state */
});
/* assert on the output */

This ensures that you're testing the behavior the user would see in the
browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
	at PlaceSelector (packages\components\src\components\domain\place\
	placeSelector\PlaceSelector.tsx...
```

refs TH-1437