fix(tests): fix hobbies Search "for accessibility violations" test
Install `canvas` package and wrap `await axe(...)` with `act`.
Remove 50s timeout from test case as unnecessary.

Previously running hobbies Search.test.tsx tests there was ~output:
```
$ yarn test src/domain/search/eventSearch/advancedSearch/__tests__/
Search.test.tsx --watch

 DEV  v3.2.4 apps/hobbies-helsinki

stderr | src/domain/search/eventSearch/advancedSearch/__tests__/
Search.test.tsx > for accessibility violations

Error: Not implemented: HTMLCanvasElement.prototype.getContext (without
installing the canvas npm package)
...

Warning: An update to PlaceSelector inside a test was not wrapped in
act(...).

When testing, code that causes React state updates should be wrapped
into act(...):

act(() => {
  /* fire events that update state */
});
/* assert on the output */

This ensures that you're testing the behavior the user would see in the
browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
    at PlaceSelector (packages\components\src\components\domain\place\
    placeSelector\PlaceSelector.tsx:63:3)
    ...
```

refs HH-452