fix(components): fix types (i.e. 3x TS2322 errors)
OtherEventTimes.test.tsx:
 - TS2322 error:
   - Property 'getEventListLinkUrl' does not exist on type
      IntrinsicAttributes & { event: EventFieldsFragment; }

SimilarEvents.test.tsx:
  - 2x TS2322 error:
    - Property 'getCardUrl' does not exist on type
      IntrinsicAttributes & SimilarEventsProps

refs LIIKUNTA-511 (noticed while testing)