fix(tests): make use-promise.test.tsx tests more robust with waitFor
Wrap some expects with `await waitFor(() => expect(...))` to add a bit
of robustness, because the following test failed once when running
packages/components tests:
```
FAIL  src/hooks/__tests__/use-promise.test.tsx > usePromise > hook >
should load, return the promise response and rerender
AssertionError: expected null to strictly equal { value: 'cool' }

- Expected:
{
  "value": "cool",
}

+ Received:
null

 ❯ src/hooks/__tests__/use-promise.test.tsx:30:35
     28|       });
     29|
     30|       expect(result.current.data).toStrictEqual(expected);
       |                                   ^
     31|       expect(result.current.isLoading).toStrictEqual(false);
     32|       expect(result.current.error).toBeNull();
```

refs TH-1437